apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb-port
      port: 8086
      targetPort: 8086
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-service
          image: my-image-influxdb
          imagePullPolicy: Never
          
      #     ports:
      #       - containerPort: 8086
      #     volumeMounts:
      #       - name: influxdb-volume
      #         mountPath: /var/lib/influxdb
      # volumes:
      #   - name: influxdb-volume
      #     persistentVolumeClaim:
      #       claimName: influxdb-volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
