apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: port-21
      port: 21
      protocol: TCP
    - name: port-30020
      port: 30020
      protocol: TCP
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
        - name: ftps-service
          image: my-image-ftps
          imagePullPolicy: Never
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - check_liveness.sh
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          ports:
          - containerPort: 21
          - containerPort: 30020
  
