apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps-port
      port: 21
      targetPort: 21
      protocol: TCP
      
    # - name: ftps-data0
    #   targetPort: 21000
    #   port: 21000
    # - name: ftps-data1
    #   targetPort: 21001
    #   port: 21001
    # - name: ftps-data2
    #   targetPort: 21002
    #   port: 21002
    # - name: ftps-data3
    #   targetPort: 21003
    #   port: 21003
    # - name: ftps-data4
    #   targetPort: 21004
    #   port: 21004
    # - name: ftps-data5
    #   targetPort: 21005
    #   port: 21005
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
        - name: ftps-service
          image: my-image-ftps
          imagePullPolicy: Never
          ports:
          - containerPort: 21
