apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin-port
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  # labels:
  #   app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin-service
        image: my-image-phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - ps aux | grep -v grep | grep php-fpm
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
